apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: gotrue
objects:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: gotrue
    name: gotrue
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: gotrue
      deploymentconfig: gotrue
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: gotrue
          deploymentconfig: gotrue
      spec:
        containers:
        - env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: DATABASE_URL
            value: gotrue:gotrue@tcp(mariadb.$(NAMESPACE).svc.cluster.local:3306)/gotrue?parseTime=true&multiStatements=true
          - name: GOTRUE_DB_DRIVER
            value: mysql
          - name: GOTRUE_JWT_SECRET
            value: ${GOTRUE_JWT_SECRET}
          - name: GOTRUE_JWT_AUD
          - name: GOTRUE_API_HOST
            value: 0.0.0.0
          - name: PORT
            value: "8080"
          - name: GOTRUE_LOG_LEVEL
            value: DEBUG
          - name: GOTRUE_DISABLE_SIGNUP
            value: "false"
          - name: GOTRUE_SITE_URL
            value: https://example.com
          - name: GOTRUE_OPERATOR_TOKEN
            value: placeholder
          - name: GOTRUE_EXTERNAL_GITLAB_CLIENT_ID
            value: 662ff81c6da0c941c089cc5d5b3710f8d28caac422faeb0d896779b43dea3ce9
          - name: GOTRUE_EXTERNAL_GITLAB_SECRET
            value: ${GOTRUE_EXTERNAL_GITLAB_SECRET}
          - name: GOTRUE_EXTERNAL_GITLAB_ENABLED
            value: "true"
          - name: GOTRUE_EXTERNAL_GITLAB_REDIRECT_URI
            value: https://gotrue-$(NAMESPACE).ocp.puzzle.ch/callback
          - name: GOTRUE_EXTERNAL_GITLAB_URL
            value: https://gitlab.puzzle.ch
          - name: GOTRUE_EXTERNAL_EMAIL_ENABLED
            value: "false"
          - name: GOTRUE_MAILER_AUTOCONFIRM
            value: "true"
          - name: GOTRUE_EXTERNAL_REDIRECTURL
            value: ${GOTRUE_EXTERNAL_REDIRECTURL}
          imagePullPolicy: Always
          name: gotrue
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - gotrue
        from:
          kind: ImageStreamTag
          name: gotrue:latest
      type: ImageChange
    - type: ConfigChange
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: gotrue
    name: gotrue

- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: gotrue
    name: alpine
  spec:
    lookupPolicy:
      local: false
    tags:
    - from:
        kind: DockerImage
        name: alpine:3.7
      importPolicy: {}
      name: "3.7"
      referencePolicy:
        type: Source

- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      app: gotrue
    name: gotrue
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: gotrue:latest
    source:
      git:
        uri: https://github.com/netlify/gotrue
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: alpine:3.7
      type: Docker
    triggers:
    - type: ImageChange
    - type: ConfigChange

- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      template: mariadb-persistent-template
    name: mariadb
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      name: mariadb
    strategy:
      activeDeadlineSeconds: 21600
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      type: Recreate
    template:
      metadata:
        labels:
          name: mariadb
      spec:
        containers:
        - env:
          - name: MYSQL_USER
            value: gotrue
          - name: MYSQL_PASSWORD
            value: gotrue
          - name: MYSQL_DATABASE
            value: gotrue
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3306
            timeoutSeconds: 1
          name: mariadb
          ports:
          - containerPort: 3306
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -i
              - -c
              - MYSQL_PWD="$MYSQL_PASSWORD" mysql -h 127.0.0.1 -u $MYSQL_USER -D $MYSQL_DATABASE
                -e 'SELECT 1'
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/lib/mysql/data
            name: mariadb-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: mariadb-data
          persistentVolumeClaim:
            claimName: mariadb
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - mariadb
        from:
          kind: ImageStreamTag
          name: mariadb:10.2
          namespace: openshift
      type: ImageChange
    - type: ConfigChange

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      template: mariadb-persistent-template
    name: mariadb
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: glusterfs-storage
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: gotrue
    name: gotrue
  spec:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: gotrue
      deploymentconfig: gotrue
    sessionAffinity: None
    type: ClusterIP
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: gotrue
    name: gotrue
  spec:
    port:
      targetPort: 8080
    tls:
      insecureEdgeTerminationPolicy: Redirect
      termination: edge
    to:
      kind: Service
      name: gotrue
      weight: 100
    wildcardPolicy: None
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: gotrue
    name: mariadb
  spec:
    ports:
    - name: mariadb
      port: 3306
      protocol: TCP
      targetPort: 3306
    selector:
      name: mariadb
    sessionAffinity: None
    type: ClusterIP
parameters:
- name: GOTRUE_JWT_SECRET
  description: The JWT Secret that is shared with the Git-Gateway
  required: true
- name: GOTRUE_EXTERNAL_GITLAB_SECRET
  description: The client secret
  required: true
- name: GOTRUE_EXTERNAL_REDIRECTURL
  description: The redirect URL
  default: https://info-test.ocp.puzzle.ch/admin/
  required: true
