image:
  repository: appuio-website-prod/nginx

replicaCount: 2

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
  hosts:
    - host: appuio.ch
      paths:
        - path: /
          pathType: ImplementationSpecific
          port: 8000
    - host: www.appuio.ch
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: appuio-ch-tls
      hosts:
        - appuio.ch
    - secretName: www-appuio-ch-tls
      hosts:
        - www.appuio.ch
