apiVersion: v1
kind: Secret
metadata:
  name: {{ include "netlify-cms.fullname" . }}-oauth
  labels:
    {{- include "netlify-cms.labels" . | nindent 4 }}
stringData:
  ORIGIN: {{ .Values.oauth.origin }}
  OAUTH_CLIENT_ID: {{ .Values.oauth.clientID }}
  OAUTH_CLIENT_SECRET: {{ .Values.oauth.clientSecret }}
