name: Test

on:
  pull_request:
    types: [ closed ]

jobs:
  main:
    name: Teardown
    runs-on: ubuntu-latest
    environment: test
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - uses: redhat-actions/oc-installer@v1
      with:
        oc_version: '3.11.286'

    - uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: https://console.appuio.ch
        openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
        insecure_skip_tls_verify: true

    - name: Add PR_NUMBER env property
      run: echo "PR_NUMBER=`echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }'`" >> $GITHUB_ENV

    - run: oc delete all -n pitc-appuio30-test -l app=appuio-${{ env.PR_NUMBER }}
