name: Test

on: pull_request

jobs:
  main:
    name: Deploy
    runs-on: ubuntu-latest
    environment:
      name: test
      url: ${{ env.ENVIRONMENT_URL }}
    steps:
    - name: Create deployment status for NetlifyCMS
      run: |
        curl -X POST -H "Content-Type:application/json" \
             -H "Authorization: token ${{ github.token }}" \
             -d '{"state": "pending", "context": "netlify-cms/preview/deploy"}' \
              "https://api.github.com/repos/appuio/website/statuses/${{ github.event.pull_request.head.sha }}"

    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Add PR_NUMBER env property
      run: echo "PR_NUMBER=`echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }'`" >> $GITHUB_ENV

    - name: Add ENVIRONMENT_URL env property
      run: echo "ENVIRONMENT_URL=https://appuio-${{ env.PR_NUMBER }}-pitc-appuio30-test.appuioapp.ch" >> $GITHUB_ENV

    - uses: Azure/docker-login@v1
      with:
        login-server: registry.puzzle.ch
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: |
        docker build . -t registry.puzzle.ch/puzzle/appuio-website:${{ github.event.pull_request.head.sha }}
        docker push registry.puzzle.ch/puzzle/appuio-website:${{ github.event.pull_request.head.sha }}

    - uses: redhat-actions/oc-installer@v1
      with:
        oc_version: '3.11.286'

    - uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: https://console.appuio.ch
        openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
        insecure_skip_tls_verify: true

    - run: oc project pitc-appuio30-test

    - uses: Azure/k8s-create-secret@v1
      with:
        namespace: 'pitc-appuio30-test'
        container-registry-url: registry.puzzle.ch
        container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
        container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        secret-name: registry-puzzle-secret
    - run: oc secrets add serviceaccount/default secrets/registry-puzzle-secret --for=pull

    - run: |
        oc process -f manifests/appuio.yml \
                   -p IMAGE_TAG=${{ github.event.pull_request.head.sha }} \
                   -p APP_POSTFIX=${{ env.PR_NUMBER }} \
                   | oc apply -f -
        oc process -f manifests/cms/github-oauth-provider.yml \
                   -p 'ORIGIN=.*.appuioapp.ch' \
                   -p OAUTH_CLIENT_ID=${{ secrets.OAUTH_CLIENT_ID }} \
                   -p OAUTH_CLIENT_SECRET=${{ secrets.OAUTH_CLIENT_SECRET }} \
                   | oc apply -f -
        oc rollout latest dc/appuio-${{ env.PR_NUMBER }} || true # could already be running
        oc rollout status dc/appuio-${{ env.PR_NUMBER }} # wait

        curl -X POST -H "Content-Type:application/json" \
             -H "Authorization: token ${{ github.token }}" \
             -d '{"state": "success", "context": "netlify-cms/preview/deploy", "description": "Deploy preview ready", "target_url": "${{ env.ENVIRONMENT_URL }}"}' \
              "https://api.github.com/repos/appuio/website/statuses/${{ github.event.pull_request.head.sha }}"
